2025-09-12T23:08:20 {"cpu": 0.22802734375, "cpu_total": 20, "cpu_usage": 0.0114013671875, "memory": 2011.0, "memory_total": 9804.0, "memory_usage": 0.2051203590371277, "pipeline_run_id": 6, "pipeline_schedule_id": 5, "pipeline_uuid": "qb_customer_backfill", "hostname": "370646b43903", "level": "INFO", "message": "Pipeline qb_customer_backfill for run 6 in schedule 5 is alive.", "timestamp": 1757718500.760762, "uuid": "c3c14d3e5aee451f8497323672c52f08"}
2025-09-12T23:08:21 {"cpu": 0.22802734375, "cpu_total": 20, "cpu_usage": 0.0114013671875, "memory": 2065.0, "memory_total": 9804.0, "memory_usage": 0.21062831497348022, "pipeline_run_id": 6, "pipeline_schedule_id": 5, "pipeline_uuid": "qb_customer_backfill", "hostname": "370646b43903", "level": "INFO", "message": "Pipeline qb_customer_backfill for run 6 in schedule 5 is alive.", "timestamp": 1757718501.349142, "uuid": "6adafb0eef244107a64bf5d1262cb0d3"}
2025-09-12T23:08:21 {"block_run_id": 11, "block_uuid": "qb_customer_loader", "pipeline_run_id": 6, "pipeline_schedule_id": 5, "pipeline_uuid": "qb_customer_backfill", "hostname": "370646b43903", "level": "INFO", "message": "Execute PipelineRun 6, BlockRun 11: pipeline qb_customer_backfill block qb_customer_loader", "timestamp": 1757718501.43378, "uuid": "4d2470fc477f434896a6e682b84a538d"}
2025-09-12T23:08:29 {"cpu": 0.23095703125, "cpu_total": 20, "cpu_usage": 0.0115478515625, "memory": 2085.0, "memory_total": 9804.0, "memory_usage": 0.21266829865361078, "pipeline_run_id": 6, "pipeline_schedule_id": 5, "pipeline_uuid": "qb_customer_backfill", "hostname": "370646b43903", "level": "INFO", "message": "Pipeline qb_customer_backfill for run 6 in schedule 5 is alive.", "timestamp": 1757718509.906796, "uuid": "41a40b5ff8264cf69ac731c99bd8bbb6"}
2025-09-12T23:08:39 {"block_run_id": 11, "block_uuid": "qb_customer_loader", "pipeline_run_id": 6, "pipeline_schedule_id": 5, "pipeline_uuid": "qb_customer_backfill", "hostname": "370646b43903", "level": "INFO", "message": "BlockRun 11 (block_uuid: qb_customer_loader) completes.", "timestamp": 1757718519.343572, "uuid": "4afecba20189488499e1e97b2095cb58"}
2025-09-12T23:08:40 {"cpu": 0.23974609375, "cpu_total": 20, "cpu_usage": 0.0119873046875, "memory": 2067.0, "memory_total": 9804.0, "memory_usage": 0.21083231334149327, "pipeline_run_id": 6, "pipeline_schedule_id": 5, "pipeline_uuid": "qb_customer_backfill", "hostname": "370646b43903", "level": "INFO", "message": "Pipeline qb_customer_backfill for run 6 in schedule 5 is alive.", "timestamp": 1757718520.028654, "uuid": "5250d5d57e47430fa777c92e4c0ce779"}
2025-09-12T23:08:40 {"block_run_id": 12, "block_uuid": "qb_customer_exporter", "pipeline_run_id": 6, "pipeline_schedule_id": 5, "pipeline_uuid": "qb_customer_backfill", "hostname": "370646b43903", "level": "INFO", "message": "Execute PipelineRun 6, BlockRun 12: pipeline qb_customer_backfill block qb_customer_exporter", "timestamp": 1757718520.291638, "uuid": "614ec6132fe24d0e96b42ffb3f3e64b7"}
2025-09-12T23:08:40 {"block_run_id": 12, "block_uuid": "qb_customer_exporter", "pipeline_run_id": 6, "pipeline_schedule_id": 5, "pipeline_uuid": "qb_customer_backfill", "hostname": "370646b43903", "level": "EXCEPTION", "message": "BlockRun 12 (block_uuid: qb_customer_exporter) failed.", "timestamp": 1757718520.588485, "uuid": "336132e73b59423a8345dd9ea3de27b2", "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1691, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1668, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1570, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1910, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2041, in _execute_block\n    exec(self.content, results)\n  File \"<string>\", line 114\n    \"source\": \"mage\",\n            ^\nSyntaxError: invalid syntax\n", "error_stack": ["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1442, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1830, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1226, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 794, in invoke\n    return callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 809, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 108, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 60, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1702, in schedule_all\n    PipelineScheduler(r).start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 197, in start\n    self.schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 333, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 640, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 122, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 199, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 353, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 317, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1235, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 464, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack()\n"], "error_stacktrace": "invalid syntax (<string>, line 114)"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1691, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1668, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1570, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1910, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2041, in _execute_block
    exec(self.content, results)
  File "<string>", line 114
    "source": "mage",
            ^
SyntaxError: invalid syntax
2025-09-12T23:08:49 {"cpu": 0.24267578125, "cpu_total": 20, "cpu_usage": 0.0121337890625, "memory": 2016.0, "memory_total": 9804.0, "memory_usage": 0.20563035495716034, "pipeline_run_id": 6, "pipeline_schedule_id": 5, "pipeline_uuid": "qb_customer_backfill", "hostname": "370646b43903", "level": "INFO", "message": "Pipeline qb_customer_backfill for run 6 in schedule 5 is alive.", "timestamp": 1757718529.745868, "uuid": "8d958cf507014181bc55b474b0b280ce"}
